Updated the script

diff --git a/jenkins/Jenkinsfile.working b/jenkins/Jenkinsfile.working
--- a/jenkins/Jenkinsfile.working
+++ b/jenkins/Jenkinsfile.working
@@ -1,8 +1,8 @@
 pipeline {
-    agent { label 'agent1' }
+    agent { label 'agent1' }  // Specify the Jenkins node label here
 
     environment {
-        REPO_URL = 'https://github.com/lherbeng/RKE2.git'  // Replace with your actual repo
+        REPO_URL = 'https://github.com/lherbeng/RKE2.git' // Replace with your actual repo
         INSTALL_SCRIPT_PATH = 'rancher/install_rke2_server.sh'
         UNINSTALL_SCRIPT_PATH = 'rancher/uninstall_rke2_server.sh'
         KUBECONFIG = '/etc/rancher/rke2/rke2.yaml'
@@ -33,7 +33,7 @@ pipeline {
 
                 // Provide execution permission to the install script
                 sh "chmod +x ${INSTALL_SCRIPT_PATH}"
-
+                
                 // Run the install script
                 sh "bash -c 'source ${INSTALL_SCRIPT_PATH}'"
             }
@@ -44,12 +44,11 @@ pipeline {
                 expression { params.ACTION == 'install' }  // Only verify if "install" is chosen
             }
             steps {
-                withEnv(["KUBECONFIG=${KUBECONFIG}"]) {
-                    // Verify that RKE2 server is running and kubectl is working
-                    sh '''
-                       kubectl get node -o wide || echo "kubectl not found or RKE2 server is not running."
-                    '''
-                }
+                // Verify that RKE2 server is running and kubectl is working
+                sh '''
+                   export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
+                   kubectl get node -o wide || echo "kubectl not found or RKE2 server is not running."
+                '''
             }
         }
 
@@ -61,8 +60,8 @@ pipeline {
                 echo 'Uninstalling RKE2...'
 
                 // Provide execution permission to the uninstall script
-                sh "chmod +x ${UNINSTALL_SCRIPT_PATH}"
-
+                sh 'chmod +x ${UNINSTALL_SCRIPT_PATH}'
+                
                 // Run the uninstall script
                 sh "./${UNINSTALL_SCRIPT_PATH}"
             }
@@ -90,3 +89,4 @@ pipeline {
         }
     }
 }
+
