Updated the script

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -5,6 +5,7 @@ pipeline {
         REPO_URL = 'https://github.com/lherbeng/RKE2.git' // Replace with your actual repo
         INSTALL_SCRIPT_PATH = 'rancher/install_rke2_server.sh'
         UNINSTALL_SCRIPT_PATH = 'rancher/uninstall_rke2_server.sh'
+        KUBECONFIG = '/etc/rancher/rke2/rke2.yaml'
     }
 
     parameters {
@@ -31,10 +32,10 @@ pipeline {
                 echo 'Installing RKE2...'
 
                 // Provide execution permission to the install script
-                sh "bash -c 'source ${INSTALL_SCRIPT_PATH}'"
+                sh 'chmod +x ${SCRIPT_PATH}'
                 
                 // Run the install script
-                sh "bash -c 'source ${INSTALL_SCRIPT_PATH} && env'"
+                sh "bash -c 'source ${INSTALL_SCRIPT_PATH}'"
             }
         }
 
@@ -44,7 +45,10 @@ pipeline {
             }
             steps {
                 // Verify that RKE2 server is running and kubectl is working
-                sh 'kubectl get node -o wide || echo "kubectl not found or RKE2 server is not running."'
+                sh '''
+                   export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
+                   kubectl get node -o wide || echo "kubectl not found or RKE2 server is not running."
+                '''
             }
         }
 
